"""add phone_number field to user

Revision ID: 7768a80a5517
Revises: 2ab187cc5714
Create Date: 2024-09-06 17:01:54.189306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7768a80a5517"
down_revision: Union[str, None] = "2ab187cc5714"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("phone_number", sa.String(length=15), nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_users_phone_number"), "users", ["phone_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_phone_number"), "users", type_="unique")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
